# Generated by Django 3.0.2 on 2020-02-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslist', '0002_carmodel_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
