# Generated by Django 3.0.2 on 2020-02-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslist', '0004_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(),
        ),
    ]
