# Generated by Django 3.0.2 on 2020-02-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslist', '0005_auto_20200204_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
