# Generated by Django 3.0.2 on 2020-02-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslist', '0006_auto_20200204_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='cars', to='carslist.Color'),
        ),
    ]
