# Generated by Django 3.0.3 on 2020-02-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carslist', '0008_auto_20200207_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('A', 'automatic'), ('M', 'manual'), (None, '')], max_length=50),
        ),
    ]
